// ============================================================
// Mock Data — Realistic production simulation data
// In production, replace with real API calls
// ============================================================

import type {
  Service, PipelineRun, Alert, MetricPoint,
  DockerContainer, DeploymentTarget, SecurityScan
} from "../types";

export const services: Service[] = [
  {
    id: "frontend",
    name: "Frontend (Nginx)",
    status: "healthy",
    uptime: "99.98%",
    latency: 42,
    requests: 18340,
    errorRate: 0.02,
    version: "1.4.2",
    environment: "production",
    lastDeploy: "2h ago",
    healthUrl: "/health",
    replicas: { running: 3, desired: 3 },
    cpu: 12,
    memory: 34,
  },
  {
    id: "api-gateway",
    name: "API Gateway",
    status: "healthy",
    uptime: "99.95%",
    latency: 128,
    requests: 82100,
    errorRate: 0.05,
    version: "2.1.0",
    environment: "production",
    lastDeploy: "6h ago",
    healthUrl: "/api/health",
    replicas: { running: 5, desired: 5 },
    cpu: 45,
    memory: 62,
  },
  {
    id: "auth-service",
    name: "Auth Service",
    status: "healthy",
    uptime: "99.99%",
    latency: 89,
    requests: 24500,
    errorRate: 0.01,
    version: "3.0.1",
    environment: "production",
    lastDeploy: "1d ago",
    healthUrl: "/auth/health",
    replicas: { running: 2, desired: 2 },
    cpu: 28,
    memory: 41,
  },
  {
    id: "database",
    name: "PostgreSQL Primary",
    status: "healthy",
    uptime: "99.99%",
    latency: 8,
    requests: 142000,
    errorRate: 0.0,
    version: "16.2",
    environment: "production",
    lastDeploy: "7d ago",
    healthUrl: "/db/health",
    replicas: { running: 1, desired: 1 },
    cpu: 67,
    memory: 78,
  },
  {
    id: "cache",
    name: "Redis Cache",
    status: "warning",
    uptime: "99.91%",
    latency: 2,
    requests: 310000,
    errorRate: 0.09,
    version: "7.2.4",
    environment: "production",
    lastDeploy: "3d ago",
    healthUrl: "/cache/health",
    replicas: { running: 2, desired: 3 },
    cpu: 82,
    memory: 91,
  },
  {
    id: "worker",
    name: "Background Workers",
    status: "critical",
    uptime: "98.40%",
    latency: 0,
    requests: 5800,
    errorRate: 1.6,
    version: "1.2.3",
    environment: "production",
    lastDeploy: "4h ago",
    healthUrl: "/worker/health",
    replicas: { running: 1, desired: 4 },
    cpu: 95,
    memory: 88,
  },
];

export const pipelineRuns: PipelineRun[] = [
  {
    id: "run-1247",
    branch: "main",
    commit: "a3f8c21",
    commitMsg: "feat: add production monitoring dashboard",
    author: "Alex Chen",
    avatar: "AC",
    status: "success",
    duration: "4m 32s",
    startedAt: "12 min ago",
    environment: "production",
    jobs: [
      { name: "🔍 Lint & Type Check", status: "success", duration: "1m 12s" },
      { name: "🔒 Security Audit", status: "success", duration: "45s" },
      { name: "🏗️ Build", status: "success", duration: "1m 38s" },
      { name: "🐳 Docker Build", status: "success", duration: "52s" },
      { name: "🚀 Deploy → Production", status: "success", duration: "5s" },
    ],
  },
  {
    id: "run-1246",
    branch: "develop",
    commit: "b7d2e45",
    commitMsg: "fix: resolve Redis connection pool exhaustion",
    author: "Sarah Kim",
    avatar: "SK",
    status: "running",
    duration: "2m 10s",
    startedAt: "2 min ago",
    environment: "staging",
    jobs: [
      { name: "🔍 Lint & Type Check", status: "success", duration: "58s" },
      { name: "🔒 Security Audit", status: "success", duration: "42s" },
      { name: "🏗️ Build", status: "running", duration: "30s" },
      { name: "🐳 Docker Build", status: "pending", duration: "" },
      { name: "🚀 Deploy → Staging", status: "pending", duration: "" },
    ],
  },
  {
    id: "run-1245",
    branch: "feature/worker-scaling",
    commit: "c9f1a78",
    commitMsg: "chore: scale worker replicas to 4",
    author: "Marcus Johnson",
    avatar: "MJ",
    status: "failed",
    duration: "3m 18s",
    startedAt: "38 min ago",
    environment: "staging",
    jobs: [
      { name: "🔍 Lint & Type Check", status: "success", duration: "1m 02s" },
      { name: "🔒 Security Audit", status: "success", duration: "41s" },
      { name: "🏗️ Build", status: "success", duration: "1m 20s" },
      { name: "🐳 Docker Build", status: "failed", duration: "15s" },
      { name: "🚀 Deploy → Staging", status: "skipped", duration: "" },
    ],
  },
  {
    id: "run-1244",
    branch: "main",
    commit: "d4e8b12",
    commitMsg: "perf: optimize nginx gzip and caching headers",
    author: "Priya Patel",
    avatar: "PP",
    status: "success",
    duration: "5m 44s",
    startedAt: "2h ago",
    environment: "production",
    jobs: [
      { name: "🔍 Lint & Type Check", status: "success", duration: "1m 22s" },
      { name: "🔒 Security Audit", status: "success", duration: "48s" },
      { name: "🏗️ Build", status: "success", duration: "2m 01s" },
      { name: "🐳 Docker Build", status: "success", duration: "1m 28s" },
      { name: "🚀 Deploy → Production", status: "success", duration: "5s" },
    ],
  },
  {
    id: "run-1243",
    branch: "main",
    commit: "e2c7d89",
    commitMsg: "security: update dependencies, patch CVE-2024-1234",
    author: "Alex Chen",
    avatar: "AC",
    status: "success",
    duration: "6m 12s",
    startedAt: "5h ago",
    environment: "production",
    jobs: [
      { name: "🔍 Lint & Type Check", status: "success", duration: "1m 15s" },
      { name: "🔒 Security Audit", status: "success", duration: "52s" },
      { name: "🏗️ Build", status: "success", duration: "2m 10s" },
      { name: "🐳 Docker Build", status: "success", duration: "1m 50s" },
      { name: "🚀 Deploy → Production", status: "success", duration: "5s" },
    ],
  },
];

export const alerts: Alert[] = [
  {
    id: "alert-001",
    severity: "critical",
    title: "Worker Replicas Below Desired",
    description: "background-worker running 1/4 replicas. 3 pods in CrashLoopBackOff.",
    service: "Background Workers",
    timestamp: "4 min ago",
    acknowledged: false,
  },
  {
    id: "alert-002",
    severity: "critical",
    title: "Redis Memory Usage Critical",
    description: "Redis cache memory at 91% (threshold: 85%). Risk of eviction.",
    service: "Redis Cache",
    timestamp: "12 min ago",
    acknowledged: false,
  },
  {
    id: "alert-003",
    severity: "high",
    title: "Redis Replica Missing",
    description: "Redis running 2/3 desired replicas. One pod failed to schedule.",
    service: "Redis Cache",
    timestamp: "18 min ago",
    acknowledged: true,
  },
  {
    id: "alert-004",
    severity: "high",
    title: "PostgreSQL CPU Spike",
    description: "Database CPU at 67% — above 60% sustained threshold. Check slow queries.",
    service: "PostgreSQL Primary",
    timestamp: "31 min ago",
    acknowledged: true,
  },
  {
    id: "alert-005",
    severity: "medium",
    title: "API Gateway P99 Latency Elevated",
    description: "P99 response time is 128ms (threshold: 100ms) for the past 15 minutes.",
    service: "API Gateway",
    timestamp: "45 min ago",
    acknowledged: true,
  },
  {
    id: "alert-006",
    severity: "low",
    title: "Dependency Update Available",
    description: "15 npm packages have minor/patch updates available. Weekly update PR ready.",
    service: "CI/CD Pipeline",
    timestamp: "6h ago",
    acknowledged: true,
  },
];

export const containers: DockerContainer[] = [
  {
    id: "a1b2c3d4",
    name: "devops-dashboard-frontend",
    image: "ghcr.io/yourorg/devops-dashboard:1.4.2",
    status: "running",
    cpu: 12.4,
    memory: 87,
    memoryLimit: 256,
    ports: ["80:80", "443:443"],
    uptime: "2 days",
    restarts: 0,
    health: "healthy",
  },
  {
    id: "e5f6g7h8",
    name: "prometheus",
    image: "prom/prometheus:v2.51.0",
    status: "running",
    cpu: 8.2,
    memory: 512,
    memoryLimit: 1024,
    ports: ["9090:9090"],
    uptime: "7 days",
    restarts: 0,
    health: "healthy",
  },
  {
    id: "i9j0k1l2",
    name: "grafana",
    image: "grafana/grafana:10.4.0",
    status: "running",
    cpu: 5.1,
    memory: 148,
    memoryLimit: 512,
    ports: ["3000:3000"],
    uptime: "7 days",
    restarts: 1,
    health: "healthy",
  },
  {
    id: "m3n4o5p6",
    name: "loki",
    image: "grafana/loki:2.9.0",
    status: "running",
    cpu: 3.8,
    memory: 256,
    memoryLimit: 512,
    ports: ["3100:3100"],
    uptime: "7 days",
    restarts: 0,
    health: "healthy",
  },
  {
    id: "q7r8s9t0",
    name: "watchtower",
    image: "containrrr/watchtower:latest",
    status: "running",
    cpu: 0.3,
    memory: 18,
    memoryLimit: 64,
    ports: [],
    uptime: "5 days",
    restarts: 0,
    health: "none",
  },
  {
    id: "u1v2w3x4",
    name: "nginx-exporter",
    image: "nginx/nginx-prometheus-exporter:1.1.0",
    status: "running",
    cpu: 0.5,
    memory: 12,
    memoryLimit: 32,
    ports: ["9113:9113"],
    uptime: "7 days",
    restarts: 0,
    health: "healthy",
  },
];

export const deploymentTargets: DeploymentTarget[] = [
  {
    name: "Production VPS",
    icon: "🖥️",
    status: "healthy",
    region: "US-East-1",
    provider: "DigitalOcean",
    url: "https://yourdomain.com",
    lastDeploy: "2h ago",
  },
  {
    name: "Staging",
    icon: "🧪",
    status: "deploying",
    region: "US-East-1",
    provider: "DigitalOcean",
    url: "https://staging.yourdomain.com",
    lastDeploy: "Just now",
  },
  {
    name: "Vercel Edge",
    icon: "▲",
    status: "healthy",
    region: "Global",
    provider: "Vercel",
    url: "https://devops-dash.vercel.app",
    lastDeploy: "3h ago",
  },
  {
    name: "Railway",
    icon: "🚂",
    status: "healthy",
    region: "US-West",
    provider: "Railway",
    url: "https://devops-dashboard.railway.app",
    lastDeploy: "3h ago",
  },
  {
    name: "Render",
    icon: "⚡",
    status: "warning",
    region: "Oregon",
    provider: "Render",
    url: "https://devops-dashboard.onrender.com",
    lastDeploy: "6h ago",
  },
  {
    name: "Docker Registry",
    icon: "🐳",
    status: "healthy",
    region: "Global",
    provider: "GitHub Packages",
    url: "ghcr.io/yourorg/devops-dashboard",
    lastDeploy: "2h ago",
  },
];

export const securityScans: SecurityScan[] = [
  {
    id: "scan-001",
    type: "dependency",
    name: "npm audit",
    status: "passed",
    findings: { critical: 0, high: 0, medium: 2, low: 5 },
    lastRun: "12 min ago",
    coverage: 100,
  },
  {
    id: "scan-002",
    type: "container",
    name: "Trivy Container Scan",
    status: "warning",
    findings: { critical: 0, high: 1, medium: 3, low: 8 },
    lastRun: "12 min ago",
    coverage: 100,
  },
  {
    id: "scan-003",
    type: "sast",
    name: "CodeQL Analysis",
    status: "passed",
    findings: { critical: 0, high: 0, medium: 0, low: 1 },
    lastRun: "2h ago",
    coverage: 94,
  },
  {
    id: "scan-004",
    type: "secrets",
    name: "Secret Detection",
    status: "passed",
    findings: { critical: 0, high: 0, medium: 0, low: 0 },
    lastRun: "12 min ago",
    coverage: 100,
  },
];

// Generate time-series data for charts
export function generateMetrics(points = 24, base = 60, variance = 20): MetricPoint[] {
  const now = Date.now();
  return Array.from({ length: points }, (_, i) => ({
    time: new Date(now - (points - i) * 3600000).toLocaleTimeString("en-US", {
      hour: "2-digit",
      minute: "2-digit",
      hour12: false,
    }),
    value: Math.max(0, Math.min(100, base + (Math.random() - 0.5) * variance)),
  }));
}

export const cpuMetrics = generateMetrics(24, 45, 30);
export const memoryMetrics = generateMetrics(24, 62, 20);
export const requestMetrics = generateMetrics(24, 800, 400);
export const errorMetrics = generateMetrics(24, 5, 8);
