import type { Plan } from '../types';

export const PLANS: Plan[] = [
  {
    id: 'free',
    name: 'Starter',
    description: 'Perfect for small teams getting started with attendance tracking.',
    price: { monthly: 0, annual: 0 },
    currency: 'USD',
    color: '#6b7280',
    features: [
      'Up to 10 employees',
      'Basic attendance tracking',
      'Daily & weekly reports',
      '1 department',
      '30-day data retention',
      'Email support',
      'Web & mobile check-in',
      'Basic dashboard',
    ],
    limits: {
      employees: 10,
      departments: 1,
      dataRetentionDays: 30,
      apiCallsPerMonth: 1000,
      reportExports: 5,
      integrations: 0,
      adminUsers: 1,
    },
    stripeProductId: 'prod_starter_free',
    stripePriceIdMonthly: 'price_free_monthly',
    stripePriceIdAnnual: 'price_free_annual',
  },
  {
    id: 'pro',
    name: 'Professional',
    description: 'For growing companies that need advanced features and integrations.',
    price: { monthly: 29, annual: 24 },
    currency: 'USD',
    color: '#6366f1',
    popular: true,
    badge: 'Most Popular',
    features: [
      'Up to 100 employees',
      'Advanced attendance analytics',
      'Real-time alerts & notifications',
      'Unlimited departments',
      '1-year data retention',
      'Priority email & chat support',
      'GPS & location tracking',
      'Slack & Teams integration',
      'Custom working hours',
      'Leave management',
      'Overtime tracking',
      'Export to CSV/Excel/PDF',
      'API access (10K calls/mo)',
      'Custom branding',
    ],
    limits: {
      employees: 100,
      departments: 'unlimited',
      dataRetentionDays: 365,
      apiCallsPerMonth: 10000,
      reportExports: 'unlimited',
      integrations: 5,
      adminUsers: 5,
    },
    stripeProductId: 'prod_professional',
    stripePriceIdMonthly: 'price_pro_monthly',
    stripePriceIdAnnual: 'price_pro_annual',
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    description: 'Full-scale solution for large organizations with custom requirements.',
    price: { monthly: 99, annual: 82 },
    currency: 'USD',
    color: '#f59e0b',
    badge: 'Best Value',
    features: [
      'Unlimited employees',
      'AI-powered insights & forecasting',
      'Advanced role-based permissions',
      'Unlimited departments',
      'Unlimited data retention',
      'Dedicated account manager',
      '24/7 phone & email support',
      'SSO / SAML integration',
      'Custom API integrations (unlimited)',
      'White-label option',
      'Audit logs & compliance reports',
      'Multi-location support',
      'Custom onboarding & training',
      'SLA guarantee (99.9% uptime)',
      'Advanced payroll integration',
      'Biometric device support',
      'Custom workflows & approvals',
    ],
    limits: {
      employees: 'unlimited',
      departments: 'unlimited',
      dataRetentionDays: 'unlimited',
      apiCallsPerMonth: 'unlimited',
      reportExports: 'unlimited',
      integrations: 'unlimited',
      adminUsers: 'unlimited',
    },
    stripeProductId: 'prod_enterprise',
    stripePriceIdMonthly: 'price_enterprise_monthly',
    stripePriceIdAnnual: 'price_enterprise_annual',
  },
];

export const getPlan = (id: string): Plan | undefined => PLANS.find(p => p.id === id);

export const formatPrice = (amount: number, currency = 'USD') => {
  if (amount === 0) return 'Free';
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency,
    minimumFractionDigits: 0,
  }).format(amount);
};
